export const pageTools = [
	{
		id: "inspect-element",
		name: "Element inspector",
		category: "On page",
		roles: ["design", "dev", "qa"],
		surface: "page",
		command: "toggle-inspect",
		description: "Hover any element for a quick HUD summary. Click to get a full deep inspection JSON with box model, typography, layout, animations, events, framework bindings, ARIA, data attributes and media info. Copy selector or full report.",
	},
	{
		id: "grid-overlay",
		name: "Layout grid & rulers",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "toggle-grid",
		description: "8px baseline grid, column guides and draggable rulers to verify spacing.",
	},
	{
		id: "outline-all",
		name: "Outline all elements",
		category: "On page",
		roles: ["design", "dev"],
		surface: "page",
		command: "toggle-outline",
		description: "Depth-coloured outlines reveal overflow, stray wrappers and broken nesting.",
	},
	{
		id: "eyedropper",
		name: "Color eyedropper",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "eyedropper",
		description: "Sample any pixel on screen (EyeDropper API) and copy the hex value.",
	},
	{
		id: "a11y-audit",
		name: "Accessibility audit",
		category: "On page",
		roles: ["a11y", "qa", "design"],
		surface: "page",
		command: "audit-a11y",
		description: "Missing alt text, unlabelled controls, heading-order jumps, low-contrast text, tab traps.",
	},
	{
		id: "seo-audit",
		name: "SEO & meta audit",
		category: "On page",
		roles: ["dev", "it"],
		surface: "page",
		command: "audit-seo",
		description: "Title, description, canonical, Open Graph, robots, hreflang, structured data and headings.",
	},
	{
		id: "link-check",
		name: "Broken link & image scan",
		category: "On page",
		roles: ["qa", "it"],
		surface: "page",
		command: "scan-links",
		description: "Find empty hrefs, javascript: links, mixed content and images that failed to load.",
	},
	{
		id: "page-metrics",
		name: "Performance snapshot",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "metrics",
		description: "TTFB, DOM ready, load, LCP, CLS, resource count and transfer weight from the Performance API.",
	},
	{
		id: "storage-inspector",
		name: "Storage inspector",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "storage",
		description: "Read localStorage, sessionStorage and cookies, with one-click clear for clean test runs.",
	},
	{
		id: "font-report",
		name: "Font & typography report",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "fonts",
		description: "Every font family, size, weight and line height actually rendered on the page.",
	},
	{
		id: "color-report",
		name: "Page color palette",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "colors",
		description: "Extract the real palette in use, ranked by frequency, ready to paste into tokens.",
	},
	{
		id: "edit-mode",
		name: "Design edit mode",
		category: "On page",
		roles: ["design", "qa"],
		surface: "page",
		command: "toggle-edit",
		description: "Make the page editable to mock copy changes and screenshot proposals.",
	},
	{
		id: "viewport-resize",
		name: "Responsive viewport tester",
		category: "On page",
		roles: ["qa", "design"],
		surface: "page",
		command: "viewport",
		description: "Show live viewport size, breakpoint bucket and device-pixel ratio while you resize.",
	},
	{
		id: "console-capture",
		name: "Console & error capture",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "console-log",
		description: "Collected console errors, warnings and unhandled rejections to attach to a bug report.",
	},
	{
		id: "zindex-scan",
		name: "Z-index & stacking scan",
		category: "On page",
		roles: ["dev", "design"],
		surface: "page",
		command: "zindex",
		description: "List the highest stacking contexts to debug modals, tooltips and sticky headers.",
	},
	{
		id: "tech-stack",
		name: "Tech stack detector",
		category: "On page",
		roles: ["dev", "it"],
		surface: "page",
		command: "stack",
		description: "Detect 50+ frameworks, CSS libs, animation engines, analytics, CMS platforms, build tools and third-party script domains.",
	},

	{
		id: "animation-scanner",
		name: "Animation scanner",
		category: "On page",
		roles: ["dev", "design"],
		surface: "page",
		command: "scan-animations",
		description: "Scan all active CSS and JavaScript animations on the page, including state, duration, easing and target selectors.",
	},
	{
		id: "event-listener-map",
		name: "Event listener map",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "scan-events",
		description: "Map all registered DOM event listeners by type and element, including inline handlers and framework bindings (React, Vue, Angular, Svelte).",
	},
	{
		id: "form-filler",
		name: "Form auto-filler (multi-step)",
		category: "On page",
		roles: ["qa", "dev"],
		surface: "page",
		command: "fill-form",
		description: "Auto-fill forms and multi-step wizards with realistic dummy test data or QA edge cases. Supports React, Vue, custom controls and auto-advance.",
		inputs: [
			{
				key: "mode",
				label: "Filling mode",
				type: "select",
				options: ["Fill current step / form", "Auto-advance multi-step wizard", "Watch & fill on step changes", "Clear form fields"],
				default: "Fill current step / form",
			},
			{
				key: "profile",
				label: "Data profile",
				type: "select",
				options: ["Realistic user data", "QA edge cases & stress test", "Clear all"],
				default: "Realistic user data",
			},
		],
	},
	{
		id: "snipping-tool",
		name: "Snipping tool",
		category: "On page",
		roles: ["qa", "design", "dev"],
		surface: "page",
		command: "snip",
		description: "Capture screenshots with freeform region selection, visible tab, scrolling full-page capture or content-only window mode.",
		inputs: [
			{
				key: "mode",
				label: "Capture mode",
				type: "select",
				options: ["Freeform region", "Visible tab", "Full page (scroll)", "Content only"],
				default: "Visible tab",
			},
		],
	},
]
