export const pageTools = [
	{
		id: "inspect-element",
		name: "Element inspector",
		category: "On page",
		roles: ["design", "dev", "qa"],
		surface: "page",
		command: "toggle-inspect",
		description: "Hover any element for size, font, colors and contrast. Click for HTML, CSS, box model, event listeners, framework bindings and copy-ready snippets.",
		keywords: ["devtools", "box model", "css", "html", "selector", "computed style", "event listeners", "react", "vue", "tailwind", "component"],
	},
	{
		id: "measure",
		name: "Measure distances",
		category: "On page",
		roles: ["design", "qa"],
		surface: "page",
		command: "toggle-measure",
		description: "Hover to see element sizes, click to pin one element, then hover another to see the pixel gaps between them. Esc exits.",
		keywords: ["ruler", "spacing", "distance", "gap", "redline", "pixels", "figma", "padding", "margin", "alt hover"],
	},
	{
		id: "grid-overlay",
		name: "Layout grid",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "toggle-grid",
		description: "8px baseline grid or a 12 column guide over the page (press G to switch) to verify alignment and spacing.",
		keywords: ["baseline", "columns", "12 column", "alignment", "spacing", "guides", "8pt"],
	},
	{
		id: "outline-all",
		name: "Outline all elements",
		category: "On page",
		roles: ["design", "dev"],
		surface: "page",
		command: "toggle-outline",
		description: "Outline every element and mark the ones causing horizontal overflow, to find stray wrappers and broken nesting.",
		keywords: ["x-ray", "debug css", "overflow", "horizontal scroll", "borders", "layout bugs"],
	},
	{
		id: "eyedropper",
		name: "Color eyedropper",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "eyedropper",
		description: "Hover elements to preview their color and click to copy the hex, or pick any pixel with the browser eyedropper.",
		keywords: ["color picker", "pipette", "hex", "sample", "pixel", "rgb"],
	},
	{
		id: "a11y-audit",
		name: "Accessibility audit",
		category: "On page",
		roles: ["a11y", "qa", "design"],
		surface: "page",
		command: "audit-a11y",
		description: "Missing alt text, unlabelled controls, heading order, low contrast text, small targets, duplicate ids and landmarks.",
		keywords: ["a11y", "wcag", "contrast", "aria", "screen reader", "alt text", "labels", "headings", "axe"],
	},
	{
		id: "seo-audit",
		name: "SEO & meta audit",
		category: "On page",
		roles: ["dev", "it"],
		surface: "page",
		command: "audit-seo",
		description: "Title, description, canonical, Open Graph, robots, hreflang, structured data and a full headings outline.",
		keywords: ["meta tags", "open graph", "twitter card", "canonical", "robots", "noindex", "headings outline", "schema", "search preview"],
	},
	{
		id: "link-check",
		name: "Broken link & image scan",
		category: "On page",
		roles: ["qa", "it"],
		surface: "page",
		command: "scan-links",
		description: "Empty hrefs, javascript: links, broken anchors, mixed content and failed images. Optionally checks the real HTTP status of every link.",
		keywords: ["404", "dead links", "broken links", "http status", "redirects", "anchors", "mixed content"],
		inputs: [
			{
				key: "checkHttp",
				label: "Check HTTP status (slower)",
				type: "checkbox",
				default: false,
				help: "Requests up to 300 links from the extension, 6 at a time. Cookies are only sent to this site.",
			},
		],
	},
	{
		id: "security-check",
		name: "Security headers & cookies",
		category: "On page",
		roles: ["security", "dev"],
		surface: "page",
		command: "security-check",
		description: "CSP, HSTS, clickjacking and other response headers, cookie flags, mixed content, insecure forms, inline handlers and third party scripts.",
		keywords: ["csp", "hsts", "headers", "cookies", "secure", "httponly", "samesite", "x-frame-options", "mixed content", "owasp", "sri"],
	},
	{
		id: "image-audit",
		name: "Image audit",
		category: "On page",
		roles: ["dev", "design", "qa"],
		surface: "page",
		command: "image-audit",
		description: "Images without dimensions (layout shift), oversized for their rendered size, missing lazy loading, missing alt, legacy formats and broken files.",
		keywords: ["images", "cls", "lazy loading", "webp", "avif", "responsive images", "srcset", "alt", "performance", "oversized"],
	},
	{
		id: "page-metrics",
		name: "Performance snapshot",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "metrics",
		description: "TTFB, FCP, LCP (with element), CLS, INP estimate, long tasks, resource count and transfer weight.",
		keywords: ["core web vitals", "lcp", "cls", "inp", "ttfb", "page speed", "lighthouse", "load time", "bundle size"],
	},
	{
		id: "storage-inspector",
		name: "Storage inspector",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "storage",
		description: "Read localStorage, sessionStorage and cookies, with one-click clear for clean test runs.",
		keywords: ["localstorage", "sessionstorage", "cookies", "clear data", "cache", "state"],
	},
	{
		id: "font-report",
		name: "Font & typography report",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "fonts",
		description: "Every font family, size, weight and line height actually rendered on the page.",
		keywords: ["typography", "fonts", "type scale", "font size", "line height", "font weight"],
	},
	{
		id: "color-report",
		name: "Page color palette",
		category: "On page",
		roles: ["design"],
		surface: "page",
		command: "colors",
		description: "Extract the real palette in use, ranked by frequency, ready to paste into tokens.",
		keywords: ["palette", "colors", "design tokens", "brand colors", "extract colors"],
	},
	{
		id: "edit-mode",
		name: "Design edit mode",
		category: "On page",
		roles: ["design", "qa"],
		surface: "page",
		command: "toggle-edit",
		description: "Select, drag, nudge, duplicate, delete and retype elements to mock changes and screenshot proposals.",
		keywords: ["contenteditable", "mockup", "move elements", "edit text", "prototype", "copy changes"],
	},
	{
		id: "viewport-resize",
		name: "Responsive viewport tester",
		category: "On page",
		roles: ["qa", "design"],
		surface: "page",
		command: "viewport",
		description: "Live viewport size, breakpoint and device pixel ratio, plus an in-page device frame for phone, tablet and desktop sizes.",
		keywords: ["responsive", "breakpoints", "mobile", "device frame", "iphone", "tablet", "dpr", "screen size"],
	},
	{
		id: "console-capture",
		name: "Console & error capture",
		category: "On page",
		roles: ["dev", "qa"],
		surface: "page",
		command: "console-log",
		description: "Console errors and warnings, uncaught exceptions, unhandled rejections, failed resource loads and CSP violations since the page loaded.",
		keywords: ["console", "errors", "exceptions", "warnings", "bug report", "logs", "stack trace", "csp violations"],
	},
	{
		id: "zindex-scan",
		name: "Z-index & stacking scan",
		category: "On page",
		roles: ["dev", "design"],
		surface: "page",
		command: "zindex",
		description: "List the highest z-index elements to debug modals, tooltips and sticky headers.",
		keywords: ["z-index", "stacking context", "layers", "overlay", "modal", "sticky"],
	},
	{
		id: "tech-stack",
		name: "Tech stack detector",
		category: "On page",
		roles: ["dev", "it"],
		surface: "page",
		command: "stack",
		description: "Detect 50+ frameworks, CSS libraries, animation engines, analytics, CMS platforms, build tools and third party script domains.",
		keywords: ["wappalyzer", "framework", "react", "next.js", "analytics", "cms", "libraries", "built with"],
	},
	{
		id: "animation-scanner",
		name: "Animation scanner",
		category: "On page",
		roles: ["dev", "design"],
		surface: "page",
		command: "scan-animations",
		description: "List running CSS animations, transitions and Web Animations with state, duration, easing and target selectors.",
		keywords: ["animations", "transitions", "keyframes", "motion", "easing", "web animations api"],
	},
	{
		id: "form-filler",
		name: "Form auto-filler (multi-step)",
		category: "On page",
		roles: ["qa", "dev"],
		surface: "page",
		command: "fill-form",
		description: "Auto-fill forms and multi-step wizards with realistic dummy test data or QA edge cases. Supports React, Vue, custom controls and auto-advance.",
		keywords: ["autofill", "test data", "fake data", "wizard", "qa", "edge cases", "dummy data"],
		inputs: [
			{
				key: "mode",
				label: "Filling mode",
				type: "select",
				options: ["Fill current step / form", "Auto-advance multi-step wizard", "Watch & fill on step changes", "Clear form fields"],
				default: "Fill current step / form",
			},
			{
				key: "profile",
				label: "Data profile",
				type: "select",
				options: ["Realistic user data", "QA edge cases & stress test", "Clear all"],
				default: "Realistic user data",
			},
		],
	},
	{
		id: "snipping-tool",
		name: "Snipping tool",
		category: "On page",
		roles: ["qa", "design", "dev"],
		surface: "page",
		command: "snip",
		description: "Capture screenshots with freeform region selection, visible tab, scrolling full-page capture or content-only window mode.",
		keywords: ["screenshot", "capture", "full page", "region", "screen grab", "png"],
		inputs: [
			{
				key: "mode",
				label: "Capture mode",
				type: "select",
				options: ["Freeform region", "Visible tab", "Full page (scroll)", "Content only"],
				default: "Visible tab",
				help: "Full page scrolls the page and stitches sections; captures are paced to stay under the browser rate limit.",
			},
		],
	},
]
